title: anaphors
description: some thoughts
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .bundle
  - Gemfile
  - Gemfile.lock
  - flake.nix
  - flake.lock
  - README.md
  - vendor
  - AGENTS.md
